<<<<<<< HEAD:project/app/migrations/0001_initial.py
# Generated by Django 4.2.4 on 2023-08-04 22:38
=======
# Generated by Django 4.1.7 on 2023-08-05 22:08
>>>>>>> yay:backend/app/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD:project/app/migrations/0001_initial.py
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=200)),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=500)),
                ("completed", models.BooleanField(default=False)),
>>>>>>> yay:backend/app/migrations/0001_initial.py
            ],
        ),
    ]
