# Generated by Django 4.1.7 on 2023-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
                ("passwordConf", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="login",
            name="passwordConf",
        ),
        migrations.AddField(
            model_name="login",
            name="keyVal",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
