# Generated by Django 4.1.7 on 2023-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_register_remove_login_passwordconf_login_keyval"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="keyVal",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="login",
            name="keyVal",
            field=models.CharField(max_length=10),
        ),
    ]
