# Generated by Django 4.1.7 on 2023-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_register_keyval_alter_login_keyval"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.CharField(max_length=1000)),
                ("answers", models.TextField(max_length=1000)),
            ],
        ),
    ]
