# Generated by Django 4.1.7 on 2023-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="answers",
            field=models.TextField(),
        ),
    ]
